services:
  postgres:
    container_name: nest-clean-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
    volumes:
    - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
